apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
   name: deployment-app-scaler
spec:
   scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: deploymentset-app

   minReplicas: 5
   maxReplicas: 10
