apiVersion: apps/v1
kind: ReplicaSet
metadata:
   name: replicaset-app
spec:
   replicas: 3
   selector:
      matchLabels:
         app: rsapp
   template:
      metadata:
         name: rs-app
         labels:
            app: rsapp
      spec:
         containers:
            - name: nginx
              image: nginx:latest
              resources:
                 limits:
                    memory: "128Mi"
                    cpu: "100m"
              ports:
                 - containerPort: 8080
