apiVersion: v1
kind: Pod
metadata:
   name: swamtest
   labels:
      app: swamtest-app
spec:
   containers:
      - name: c1
        image: ichte/swarmtest:node
        resources:
           limits:
              memory: "150M"
              cpu: "100m"
        ports:
           - containerPort: 8085
           # - containerPort: 8086
